site: Fluid
title: Fluid
description: >
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Calcutta
data-theme: light # default theme "dark" | "light"

author:
  name: Anbu
  bio: Catch em' thoughts
  email: hi@anbuu.in # email adress

# URL settings
url: "https://fluid.anbuu.in" #
baseurl: "" # leave blank if not wishd
permalink: "https://fluid.anbuu.in/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


